"""Collect 300 real public pages for the first isolated research library."""

from __future__ import annotations

import csv
import hashlib
import io
import json
import shutil
import subprocess
import sys
import time
import zipfile
from collections.abc import Iterable
from pathlib import Path
from typing import Any

import pyarrow.parquet as pq
from PIL import Image, ImageOps

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from scripts.audit_public_dataset_200 import difference_hash
from scripts.collect_public_dataset_200 import (
    COMMONS_API,
    FUNSD_URL,
    USER_AGENT,
    XFUND_URL,
    commons_files,
    normalized_jpeg_bytes,
    request_json,
    strip_html,
)


EXISTING_IMAGE_DIR = PROJECT_ROOT / "data/incoming/200页全部放这里"
EXISTING_SOURCE_CSV = (
    PROJECT_ROOT / "data/evaluation/public_dataset_200_sources.csv"
)
OUTPUT_DIR = PROJECT_ROOT / "data/incoming/expansion_300_real"
CACHE_DIR = PROJECT_ROOT / "work/dataset_500_cache"
SOURCE_CSV = (
    PROJECT_ROOT
    / "data/evaluation/public_dataset_expansion_300_sources.csv"
)
SUMMARY_PATH = (
    PROJECT_ROOT
    / "data/evaluation/public_dataset_expansion_300_summary.json"
)
CORD_PARQUET = (
    CACHE_DIR
    / "cord_v2/data/test-00000-of-00001-9c204eb3f4e11791.parquet"
)
CORD_URL = (
    "https://hf-mirror.com/datasets/naver-clova-ix/cord-v2/"
    "resolve/main/data/test-00000-of-00001-9c204eb3f4e11791.parquet"
)
CORD_DATASET_URL = "https://huggingface.co/datasets/naver-clova-ix/cord-v2"
IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".webp", ".bmp", ".tif", ".tiff"}

CATEGORY_TARGETS = {
    "clear_document": 25,
    "table_form_ticket": 149,
    "degraded_document": 126,
}
SOURCE_TARGETS = {
    "XFUND Chinese train": 75,
    "FUNSD": 126,
    "CORD v2 test": 99,
}
COMMONS_PLANS = [
    (
        "scene_text",
        35,
        ["Road signs in China", "Shop signs in China", "Information boards in China", "Signs in China"],
        True,
        "zh_or_mixed",
        "real_scene_photo",
    ),
    (
        "ppt_poster_slide",
        25,
        ["Posters of China", "Advertisements in China", "Advertising in China"],
        True,
        "mixed",
        "real_poster_or_advertisement",
    ),
    (
        "complex_academic",
        25,
        ["Documents of China", "Maps of China"],
        True,
        "mixed",
        "real_scan_or_map",
    ),
    (
        "software_web_code",
        25,
        ["Screenshots of software"],
        True,
        "mixed",
        "real_software_screenshot",
    ),
    (
        "natural_no_text",
        40,
        ["Landscapes of China", "Mountains of China", "Lakes of China", "Parks in China", "Rivers of China"],
        False,
        "none",
        "real_natural_photo",
    ),
]
AI_MARKERS = (
    "ai-generated",
    "ai generated",
    "midjourney",
    "dall-e",
    "stable diffusion",
    "generated by ai",
    "artificial intelligence generated",
)
COMMONS_DOWNLOAD_DELAY_SECONDS = 1.1


def read_csv(path: Path) -> list[dict[str, str]]:
    with path.open("r", encoding="utf-8-sig", newline="") as handle:
        return list(csv.DictReader(handle))


def image_members(path: Path) -> list[str]:
    with zipfile.ZipFile(path) as archive:
        return sorted(
            info.filename
            for info in archive.infolist()
            if not info.is_dir()
            and Path(info.filename).suffix.lower() in IMAGE_SUFFIXES
        )


def dhash_from_jpeg(payload: bytes) -> int:
    with Image.open(io.BytesIO(payload)) as image:
        grayscale = ImageOps.grayscale(
            ImageOps.exif_transpose(image)
        ).resize((9, 8))
    pixels = list(grayscale.get_flattened_data())
    value = 0
    for row in range(8):
        for column in range(8):
            left = pixels[row * 9 + column]
            right = pixels[row * 9 + column + 1]
            value = (value << 1) | int(left > right)
    return value


class Curator:
    def __init__(self, output_dir: Path) -> None:
        self.output_dir = output_dir
        self.rows: list[dict[str, Any]] = []
        self.hashes: set[str] = set()
        self.dhashes: list[int] = []
        self.counts: dict[str, int] = {}
        self.existing_commons_titles: set[str] = set()
        for path in sorted(EXISTING_IMAGE_DIR.glob("*.jpg")):
            self.hashes.add(hashlib.sha256(path.read_bytes()).hexdigest())
            self.dhashes.append(difference_hash(path))
        for row in read_csv(EXISTING_SOURCE_CSV):
            if row["source_name"] == "Wikimedia Commons":
                self.existing_commons_titles.add(row["source_file"])

    def add(
        self,
        payload: bytes,
        *,
        category: str,
        has_text: bool,
        language: str,
        quality_tags: str,
        source_name: str,
        source_url: str,
        source_file: str,
        license_name: str,
        license_url: str,
        author: str,
        origin_type: str,
    ) -> bool:
        try:
            jpeg, width, height = normalized_jpeg_bytes(payload)
        except Exception:
            return False
        digest = hashlib.sha256(jpeg).hexdigest()
        dhash = dhash_from_jpeg(jpeg)
        if digest in self.hashes:
            return False
        if any((dhash ^ previous).bit_count() <= 5 for previous in self.dhashes):
            return False

        index = self.counts.get(category, 0) + 1
        filename = f"expansion_{category}_{index:03d}.jpg"
        target = self.output_dir / filename
        target.write_bytes(jpeg)
        self.hashes.add(digest)
        self.dhashes.append(dhash)
        self.counts[category] = index
        self.rows.append(
            {
                "item_id": digest[:16],
                "filename": filename,
                "category": category,
                "language": language,
                "has_text": str(has_text).lower(),
                "quality_tags": quality_tags,
                "source_name": source_name,
                "source_url": source_url,
                "source_file": source_file,
                "license": license_name,
                "license_url": license_url,
                "author": author,
                "origin_type": origin_type,
                "ai_generated": "false",
                "declared_ai_generated_percent": "0",
                "hard_negative_group": (
                    f"expansion_{category}_{(index - 1) // 2 + 1:03d}"
                    if index <= 20
                    else ""
                ),
                "width": width,
                "height": height,
                "review_status": "待人工审核",
                "dataset_name": "public_dataset_500_expansion",
                "perceptual_group": "",
                "privacy_review_required": "false",
                "category_review_required": "false",
            }
        )
        return True


def collect_archive(
    curator: Curator,
    archive_path: Path,
    assignments: list[tuple[str, int]],
    *,
    source_name: str,
    source_url: str,
    license_name: str,
    license_url: str,
    language: str,
    quality_tags: str,
    origin_type: str,
    author: str,
) -> None:
    members = image_members(archive_path)
    cursor = 0
    with zipfile.ZipFile(archive_path) as archive:
        for category, required in assignments:
            created = 0
            while created < required and cursor < len(members):
                member = members[cursor]
                cursor += 1
                if curator.add(
                    archive.read(member),
                    category=category,
                    has_text=True,
                    language=language,
                    quality_tags=quality_tags,
                    source_name=source_name,
                    source_url=source_url,
                    source_file=member,
                    license_name=license_name,
                    license_url=license_url,
                    author=author,
                    origin_type=origin_type,
                ):
                    created += 1
            if created != required:
                raise RuntimeError(
                    f"{source_name}: collected {created}/{required} "
                    f"for {category}"
                )


def cord_image_bytes(value: Any) -> bytes | None:
    if isinstance(value, dict):
        payload = value.get("bytes")
        if isinstance(payload, bytes):
            return payload
    if isinstance(value, bytes):
        return value
    return None


def collect_cord(curator: Curator, required: int = 50) -> None:
    if not CORD_PARQUET.is_file():
        raise FileNotFoundError(
            f"Download CORD parquet first: {CORD_PARQUET}"
        )
    table = pq.read_table(CORD_PARQUET, columns=["image"])
    created = 0
    for index, scalar in enumerate(table.column("image")):
        payload = cord_image_bytes(scalar.as_py())
        if payload is None:
            continue
        if curator.add(
            payload,
            category="table_form_ticket",
            has_text=True,
            language="id",
            quality_tags="real_receipt,photo_or_scan",
            source_name="CORD v2 test",
            source_url=CORD_DATASET_URL,
            source_file=f"test_row_{index:03d}",
            license_name="CC BY 4.0",
            license_url="https://creativecommons.org/licenses/by/4.0/",
            author="NAVER CLOVA",
            origin_type="real_receipt",
        ):
            created += 1
        if created == required:
            return
    raise RuntimeError(f"CORD: collected {created}/{required}")


def metadata_text(metadata: dict[str, Any]) -> str:
    return " ".join(
        strip_html(str(value.get("value", "")))
        for value in metadata.values()
        if isinstance(value, dict)
    ).lower()


def commons_image_info_batches(
    titles: list[str],
) -> Iterable[tuple[str, dict[str, Any]]]:
    for start in range(0, len(titles), 50):
        batch = titles[start : start + 50]
        payload = request_json(
            COMMONS_API,
            {
                "action": "query",
                "format": "json",
                "prop": "imageinfo",
                "titles": "|".join(batch),
                "iiprop": "url|extmetadata|mime|size",
                "iiurlwidth": "1600",
            },
        )
        for page in payload["query"]["pages"].values():
            info = (page.get("imageinfo") or [None])[0]
            if info is not None:
                yield page["title"], info


def request_image_bytes(url: str) -> bytes:
    """Download one bounded Commons image with polite throttling and retries."""
    time.sleep(COMMONS_DOWNLOAD_DELAY_SECONDS)
    try:
        completed = subprocess.run(
            [
                "curl.exe",
                "-sS",
                "-L",
                "--fail",
                "--connect-timeout",
                "8",
                "--max-time",
                "30",
                "--max-filesize",
                str(15 * 1024 * 1024),
                "--retry",
                "6",
                "--retry-all-errors",
                "--retry-delay",
                "10",
                "--retry-max-time",
                "90",
                "-H",
                f"User-Agent: {USER_AGENT}",
                url,
            ],
            check=False,
            capture_output=True,
            timeout=105,
        )
    except subprocess.TimeoutExpired as error:
        raise RuntimeError("Commons image exceeded 105-second limit") from error
    if completed.returncode != 0:
        raise RuntimeError(
            completed.stderr.decode(errors="replace")[-300:]
        )
    return completed.stdout


def collect_commons_plan(
    curator: Curator,
    category: str,
    required: int,
    commons_categories: Iterable[str],
    has_text: bool,
    language: str,
    origin_type: str,
) -> None:
    accepted_license_prefixes = ("CC BY", "CC0", "Public domain", "PDM")
    created = 0
    seen_titles: set[str] = set()
    for commons_category in commons_categories:
        titles = commons_files(commons_category, limit=400)
        for title, info in commons_image_info_batches(titles):
            if (
                title in seen_titles
                or title in curator.existing_commons_titles
            ):
                continue
            seen_titles.add(title)
            try:
                if not str(info.get("mime", "")).startswith("image/"):
                    continue
                metadata = info.get("extmetadata", {})
                if any(marker in metadata_text(metadata) for marker in AI_MARKERS):
                    continue
                license_name = strip_html(
                    metadata.get("LicenseShortName", {}).get("value", "")
                )
                if not license_name.startswith(accepted_license_prefixes):
                    continue
                image_url = info.get("thumburl")
                if not image_url:
                    continue
                payload = request_image_bytes(image_url)
                author = strip_html(
                    metadata.get("Artist", {}).get("value", "")
                    or metadata.get("Credit", {}).get("value", "")
                )
                accepted = curator.add(
                    payload,
                    category=category,
                    has_text=has_text,
                    language=language,
                    quality_tags=origin_type,
                    source_name="Wikimedia Commons",
                    source_url=info.get("descriptionurl", ""),
                    source_file=title,
                    license_name=license_name,
                    license_url=metadata.get("LicenseUrl", {}).get("value", ""),
                    author=author,
                    origin_type=origin_type,
                )
            except Exception as error:
                print(f"skip Commons {title}: {error}")
                continue
            if accepted:
                created += 1
                curator.existing_commons_titles.add(title)
                print(f"Commons {category}: {created}/{required}")
            if created == required:
                return
    raise RuntimeError(f"Commons {category}: collected {created}/{required}")


def validate(curator: Curator) -> dict[str, Any]:
    if len(curator.rows) != 300:
        raise RuntimeError(f"Expected 300 rows, found {len(curator.rows)}")
    if curator.counts != CATEGORY_TARGETS:
        raise RuntimeError(f"Category mismatch: {curator.counts}")
    source_counts: dict[str, int] = {}
    total_bytes = 0
    for row in curator.rows:
        source_counts[row["source_name"]] = (
            source_counts.get(row["source_name"], 0) + 1
        )
        total_bytes += (curator.output_dir / row["filename"]).stat().st_size
    if source_counts != SOURCE_TARGETS:
        raise RuntimeError(f"Source mismatch: {source_counts}")
    return {
        "status": "collected_and_automatically_audited",
        "page_count": 300,
        "category_counts": curator.counts,
        "source_counts": source_counts,
        "exact_duplicates_with_existing_or_new": 0,
        "perceptual_near_duplicates_with_existing_or_new": 0,
        "declared_ai_generated_percent": 0,
        "human_provenance_review_required": True,
        "total_size_mb": round(total_bytes / 1024**2, 2),
    }


def main() -> None:
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    if hasattr(sys.stderr, "reconfigure"):
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    if OUTPUT_DIR.exists() and any(OUTPUT_DIR.iterdir()):
        if SOURCE_CSV.is_file() and SUMMARY_PATH.is_file():
            print(SUMMARY_PATH.read_text(encoding="utf-8"))
            return
        raise RuntimeError(f"Incomplete non-empty output: {OUTPUT_DIR}")

    build_dir = (
        PROJECT_ROOT
        / "work"
        / f"expansion_300_build_{int(time.time())}"
    )
    build_dir.mkdir(parents=True, exist_ok=False)
    curator = Curator(build_dir)
    try:
        collect_archive(
            curator,
            CACHE_DIR.parent / "dataset_200_cache/xfund_zh_train.zip",
            [("clear_document", 25), ("table_form_ticket", 50)],
            source_name="XFUND Chinese train",
            source_url=XFUND_URL,
            license_name="CC BY-NC-SA 4.0",
            license_url="https://creativecommons.org/licenses/by-nc-sa/4.0/",
            language="zh",
            quality_tags="real_form,clear_scan",
            origin_type="real_form_scan",
            author="XFUND authors",
        )
        print("XFUND: 75/75")
        collect_archive(
            curator,
            CACHE_DIR.parent / "dataset_200_cache/funsd.zip",
            [("degraded_document", 126)],
            source_name="FUNSD",
            source_url=FUNSD_URL,
            license_name="Non-commercial research and educational use",
            license_url="https://guillaumejaume.github.io/FUNSD/",
            language="en",
            quality_tags="real_form,low_resolution,scan_noise",
            origin_type="real_noisy_form_scan",
            author="FUNSD authors",
        )
        print("FUNSD: 126/126")
        collect_cord(curator, required=99)
        print("CORD: 99/99")
        summary = validate(curator)

        OUTPUT_DIR.parent.mkdir(parents=True, exist_ok=True)
        shutil.move(str(build_dir), str(OUTPUT_DIR))
        SOURCE_CSV.parent.mkdir(parents=True, exist_ok=True)
        with SOURCE_CSV.open(
            "w", encoding="utf-8-sig", newline=""
        ) as handle:
            writer = csv.DictWriter(
                handle, fieldnames=list(curator.rows[0])
            )
            writer.writeheader()
            writer.writerows(curator.rows)
        SUMMARY_PATH.write_text(
            json.dumps(summary, ensure_ascii=False, indent=2) + "\n",
            encoding="utf-8",
        )
    except Exception:
        print(f"partial build kept for diagnosis: {build_dir}")
        raise
    print(json.dumps(summary, ensure_ascii=False, indent=2))
    print(OUTPUT_DIR)


if __name__ == "__main__":
    main()
